export const nameDict = {
    artmuseums: ['Art', '🎨'],
    museums: ['Museums', '🖼️'],
    wine_bars: ['Wine', '🍷'],
    speakeasies: ['Speakeasies', '🥃'],
    japanese: ['Japanese', '🍱'],
    bars: ['Bars', '🍺'],
    barbeque: ['Barbeque', '🍖'],
    extreme: ['Extreme', '🧨'],
    cafe: ['Cafe', '☕'],
    bakeries: ['Bakeries', '🥖'],
    danceclubs: ['Clubs', '​🍾​'],
    tea: ['Tea', '🍵'],
    chinese: ['Chinese', '🥡'],
    newamerican: ['American', '🥩'],
    poke: ['Poke', '🍚'],
    acaibowl: ['Acai', '🍓'],
    burgers: ['Burgers', '🍔'],
    dancing: ['Dancing', '💃'],
    pizza: ['Pizza', '🍕'],
    yoga: ['Yoga', '🧘'],
    karaoke: ['Karaoke', '🎤'],
    icecream: ['Ice Cream', '🍦'],
    arcades: ['Arcades', '👾'],
    mexican: ['Mexican', '🌮'],
    oriental: ['Indian', '🇮🇳'],
    sushi: ['Sushi', '🍣'],
    markets: ['Markets', '🏬'],
    parks: ['Parks', '🌲'],
    sandwiches: ['Sandwiches', '🥪'],
    artgalleries: ['Galleries', '🖌️'],
    gelato: ['Gelato', '🍨'],
    italian: ['Italian', '🍝'],
    spa: ['Spa', '🧖‍♀️'],
    cocktailbars: ['Cocktails', '🍸'],
    pubs: ['Pubs', '🍻'],
    rockclimbing: ['Rock Climbing', '🧗'],
    comedyclubs: ['Comedy Clubs', '🤣']
};
